### ISSUE TITLE
选择zfs raid1只利用200G空间，创建PVE后扩容ZFS空间

### ISSUE THREAD

**Issue by Xiar4119** [firemakergk/aquar-build-helper#11]
Ref:
https://zhuanlan.zhihu.com/p/76736235
https://blog.csdn.net/sx_1706/article/details/127673151?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-127673151-blog-44958661.235%5Ev31%5Epc_relevant_default_base3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-127673151-blog-44958661.235%5Ev31%5Epc_relevant_default_base3&utm_relevant_index=2
https://blog.csdn.net/cclethe/article/details/126341073?spm=1001.2101.3001.6650.5&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7ERate-5-126341073-blog-129358074.235%5Ev31%5Epc_relevant_default_base3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7ERate-5-126341073-blog-129358074.235%5Ev31%5Epc_relevant_default_base3&utm_relevant_index=10

正文：
ls -l /dev/disk/by-id/
lrwxrwxrwx 1 root root  9 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280065 -> ../../sdc
lrwxrwxrwx 1 root root 10 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280065-part1 -> ../../sdc1
lrwxrwxrwx 1 root root 10 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280065-part2 -> ../../sdc2
lrwxrwxrwx 1 root root 10 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280065-part3 -> ../../sdc3
lrwxrwxrwx 1 root root  9 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280072 -> ../../sda
lrwxrwxrwx 1 root root  9 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280075 -> ../../sdb
lrwxrwxrwx 1 root root 10 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280075-part1 -> ../../sdb1
lrwxrwxrwx 1 root root 10 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280075-part2 -> ../../sdb2
lrwxrwxrwx 1 root root 10 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280075-part3 -> ../../sdb3
lrwxrwxrwx 1 root root  9 Apr 21 21:29 ata-GLOWAY_STK2TS3-S7_202303280127 -> ../../sdd
![image](https://user-images.githubusercontent.com/32267029/233690686-59d8e0df-ec50-4237-bb67-1302310f6632.png)
记录ZFS分区硬盘ID
ata-GLOWAY_STK2TS3-S7_202303280065-part3 -> ../../sdc3
ata-GLOWAY_STK2TS3-S7_202303280075-part3 -> ../../sdb3
fdisk /dev/sdb -d删除sdb3, n新建300G sdb3,w 退出
fdisk /dev/sdc -d删除sdc3, n新建300G sdc3,w 退出
zpool online -e rpool ata-GLOWAY_STK2TS3-S7_202303280065-part3
zpool online -e rpool ata-GLOWAY_STK2TS3-S7_202303280065-part3
![image](https://user-images.githubusercontent.com/32267029/233690997-2ba48c49-bbcf-4cd4-a186-7be0bbc02e9b.png)

**Comment by firemakergk** [comment]
感谢你为这个项目做贡献！
