### ISSUE TITLE
请教pve相关安装和配置问题

### ISSUE THREAD

**Issue by HomengLau** [firemakergk/aquar-build-helper#14]
看了下pve安装篇和window安装篇。配置不是很详细。
我使用了I9的处理器和华硕的主板。独立显卡，用来安装pve是不是损耗很多的性能。
请教下几个问题：
    1. pve需要做对应的磁盘分区吗？我是用来一个2T的固态m.2
    2. 对于IDE通道这块需要怎么处理我看挂载两个ISO的时候会报错
    3. 我主要是需要一台window和附带Linux系统，对于window系统硬件方面需要如何配置才能最大发挥硬件的系统

**Comment by firemakergk** [comment]
1.固态盘被pve纳入存储管理以后你就可以按自己的需求自行分配它的用途了，比如说1T给ubuntu，另1T给Windows，然后这1T你可以在操作系统里面再自行分区。
2.我一般一个个挂载，免得出现冲突，就是装系统的时候挂一个，装驱动的时候把第一个卸载，再装另一个。
3.我只能给你些有限的建议，比如说cpu的类型选host、网络选virtualIO、显卡尽量直通、如果外挂硬盘尽量直通等等，文档中也都有提到。
