### ISSUE TITLE
filerun启动失败

### ISSUE THREAD

**Issue by junyuyuan** [firemakergk/aquar-build-helper#16]
![image](https://github.com/firemakergk/aquar-build-helper/assets/11531378/b4ca3bec-f564-4105-b589-938ed9248d1e)

docker compose:

  filerun:
    image: filerun/filerun:8.1
    container_name: filerun
    environment:
      FR_DB_HOST: mariadb
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: root
      FR_DB_PASS: root
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 1000
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 1000
    depends_on:
      - mariadb
    ports:
      - "8008:80"
    volumes:
      - /opt/aquar/storages/apps/filerun/html:/var/www/html
      - /opt/aquar/storages/aquarpool:/user-files

如果直接填写 image: filerun/filerun
报错：
aquar docker services starting
Pulling filerun (filerun/filerun:)...
ERROR: manifest for filerun/filerun:latest not found: manifest unknown: manifest unknown

填写 8.1版本后，docker无法拉起

**Comment by junyuyuan** [comment]
更换了docker源之后修复

**Comment by firemakergk** [comment]
上周filerun把他们的docker镜像仓库清空了，只留了一个7.X版本和一个8.1版本，我还试了一下，虽然容器起来了，但web页面进不去，我记得报一个403的权限错误，目前没找到什么文档，只能再等等了。

**Comment by junyuyuan** [comment]
网易云 https://hub-mirror.c.163.com

阿里云 https://ustc-edu-cn.mirror.aliyuncs.com

Github https://ghcr.io

我是添加了这三个docker镜像地址后恢复正常的，具体是上面哪个生效了就不太清楚了，目前运转良好。

**Comment by firemakergk** [comment]
你目前在哪个版本上？我回头试试

**Comment by junyuyuan** [comment]
filerun:
    image: filerun/filerun
    container_name: filerun
    environment:
      FR_DB_HOST: mariadb
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: root
      FR_DB_PASS: root
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 1000
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 1000
    depends_on:
      - mariadb
    ports:
      - "8008:80"
    volumes:
      - /opt/aquar/storages/apps/filerun/html:/var/www/html
      - /opt/aquar/storages/aquarpool:/user-files
    restart: unless-stopped

用的这套compose，应该是和aquarhome里面自带的一样的。

**Comment by junyuyuan** [comment]
没有标记版本

**Comment by firemakergk** [comment]
哦，那就是latest，我当时遇到问题的时候latest上都没有东西的，也许现在官方已经修了。

**Comment by junyuyuan** [comment]
我之前的测试是，不添加镜像失败，添加了之后修复

**Comment by junyuyuan** [comment]
docker hub上看到的好像还是只有8.1和7.4两个版本
