### ISSUE TITLE
想请教一下 Linux 系统下 NFS 目录的挂载问题

### ISSUE THREAD

**Issue by SinclairLin** [firemakergk/aquar-build-helper#22]
使用 mount 挂载 nfs 目录时提示权限错误：
```
~ mount -t nfs 192.168.172.2:/xxx /mnt/xxx         
mount.nfs: access denied by server while mounting 192.168.172.2:/xxx
```
但是使用 showmount 命令查看，该目录允许所有主机(*)挂载：
```
~ showmount -e 192.168.172.2                                         
Export list for 192.168.172.2:
/xxx *
```
其中，`/xxx`为 NAS 上设置的NFS目录，请问有没有什么排查思路？

**Comment by KrDw9ec4** [comment]
如果要共享池对应的数据集，则需要在命令行把池文件夹的所有权改为你要挂载系统用户对应的 id。
如果只是共享一个普通的数据集，则在 UI 编辑其权限为你要挂载系统用户对应的 id。
[truenas下配置用户及权限](https://github.com/firemakergk/aquar-build-helper/blob/master/details/truenas%E4%B8%8B%E9%85%8D%E7%BD%AE%E7%94%A8%E6%88%B7%E5%8F%8A%E6%9D%83%E9%99%90.md) 这里有提一嘴。
