### ISSUE TITLE
win10 核显直通HDMI没有显示

### ISSUE THREAD

**Issue by kvkang** [firemakergk/aquar-build-helper#7]
CPU: I5 - 10400
主板: 微星 B560M MORTOR 迫击炮 D4
PVE版本: 7.4-3

现象
1. 任务管理器可以看到核显,但接HDMI线看不到任何输出

**Comment by kvkang** [comment]
大佬们有遇到过这种问题吗?

**Comment by firemakergk** [comment]
核显直通一直没条件深度研究，暂时提供不了什么帮助，不过有一个“佛西博客”在这方面非常有积累，你可以搜搜看
