### ISSUE TITLE
为什么要配置为dhcp

### ISSUE THREAD

**Issue by mss-x** [firemakergk/aquar-build-helper#8]
为什么要配置为dhcp？静态ip有什么问题不能用？

**Comment by firemakergk** [comment]
pve默认的设置一旦你更换了路由器，或改变了网段以后，会导致pve因为网段不一致而无法联网，就算插显示器也只能看到之前他自己记录的静态ip，你必需从物理设备上手动修改配置文件才能让她重新恢复联网，这是非常麻烦的。相比之下dhcp虽然有可能ip飘移，但设备终究是在网的，可以远程控制它。而解决ip飘移也很简单，你只需要在路由器上给pve的mac地址一个固定ip即可。
